[[stack]]
name = "leetcode-preparation"

[stack.config]
server = "<your-server>"
repo = "umbertocicciaa/leetcode-preparation"
branch = "main"
file_paths = ["compose.yaml"]
run_build = true
environment = """
POSTGRES_DB = leetcode
POSTGRES_USER = leetcode
POSTGRES_PASSWORD = [[POSTGRES_PASSWORD]]
APP_PORT = 3000
PROXY_NETWORK = proxy
"""
